
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('users').insert({
          email: 'cooper.heinrichs@gmail.com',
          phone: '3035892321',
          first_name: 'Cooper',
          last_name: 'Heinrichs',
          password: 'password',
          portrait_link: 'https://pbs.twimg.com/profile_images/628693396874334208/iLMsLBUk.jpg',
          message_notifications: true,
          group_notifications: true,
          broadcast_notifications: true,
          country_code: 1,
          account_created: knex.fn.now(),
          user_latitude: '40.167207',
          user_longitude: '-105.101927',
          verified: true,
          last_login: knex.fn.now(),
          banned: false,
          ban_timestamp: null,
          discipline: 'Hunter/Jumper',
          confirmation_code: '54HW',
          user_type: 'App',
          ip_address: '69.170.209.157',
          tutorial_1: true,
          tutorial_2: true,
          tutorial_3: true,
          tutorial_4: true,
          tutorial_5: true,
          EULA: true,
          EULA_date_agreed: knex.fn.now()
        }),
        knex('users').insert({
          email: 'morgan.heinrichs@gmail.com',
          phone: '3035892486',
          first_name: 'Morgan',
          last_name: 'Heinrichs',
          password: 'password',
          portrait_link: 'http://horsesdaily.com/sites/default/files/styles/article-auto/public/109764.jpg?itok=pdCnYJwA',
          message_notifications: true,
          group_notifications: true,
          broadcast_notifications: true,
          country_code: 1,
          account_created: knex.fn.now(),
          user_latitude: '40.167207',
          user_longitude: '-105.101927',
          verified: true,
          last_login: knex.fn.now(),
          banned: false,
          ban_timestamp: null,
          discipline: 'Drassage',
          confirmation_code: '3X1P',
          user_type: 'App',
          ip_address: '69.170.209.157',
          tutorial_1: false,
          tutorial_2: false,
          tutorial_3: true,
          tutorial_4: false,
          tutorial_5: true,
          EULA: true,
          EULA_date_agreed: knex.fn.now()
        }),
        knex('users').insert({
          email: 'george.heinrichs@gmail.com',
          phone: '3033484286',
          first_name: 'George',
          last_name: 'Heinrichs',
          password: 'password',
          portrait_link: 'https://i.vimeocdn.com/portrait/11888103_300x300.jpg',
          message_notifications: true,
          group_notifications: true,
          broadcast_notifications: true,
          country_code: 1,
          account_created: knex.fn.now(),
          user_latitude: '40.167207',
          user_longitude: '-105.101927',
          verified: true,
          last_login: knex.fn.now(),
          banned: false,
          ban_timestamp: null,
          discipline: 'Quarterhorse',
          confirmation_code: '54HW',
          user_type: 'App',
          ip_address: '69.170.209.157',
          tutorial_1: true,
          tutorial_2: true,
          tutorial_3: true,
          tutorial_4: true,
          tutorial_5: true,
          EULA: true,
          EULA_date_agreed: knex.fn.now()
        })
      ]);
    });
};
